### ISSUE TITLE
How to handle C++ 17 specific code

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/brainvisa-cmake#101]
Some code in soma-io have C++ 17 specific code that requires `g++` options to be compiled without error (see https://github.com/brainvisa/soma-io/issues/30). These options are included via the following CMake variables that are only defined if compilation system is Ubuntu >= 22.04:
```
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```
Since we started using C++ 17 specific code, inclusion of these options should be done for all systems. For instance, I need these lines to compile with Conda (gcc 13.1.0) on Ubuntu 20.04.

**Comment by denisri** [comment]
Technically this is more a project-level setting (needed for soma-io but not necessarily for a custom project) but it's easier to set it globally in brainvisa-cmake, sure.
Otherwise I don't know if it would be possible to set it in soma-io `CMakeLists`, but it should be exported globally so that all projects, or all dependent projects, also inherit this setting.
Anyway I'm OK to set it in brainvisa-cmake.
