### ISSUE TITLE
Compilation broken on the master branch

### ISSUE THREAD

**Issue by ylep** [brainvisa/brainvisa-cmake#106]
In a fresh build directory, compilation fails. Maybe a side effect of the conda-related changes?

```
CMake Error at /casa/host/bootstrap/brainvisa-cmake/share/brainvisa-cmake-5.2/cmake/brainvisa-cmake-config.cmake:938 (add_custom_target):
  add_custom_target cannot create target "anatomist" because another target
  with the same name already exists.  The existing target is a shared library
  created in source directory
  "/casa/host/src/anatomist/anatomist-free/master/src/lib".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  /casa/host/bootstrap/brainvisa-cmake/share/brainvisa-cmake-5.2/cmake/brainvisa-cmake-config.cmake:1785 (BRAINVISA_COPY_FILES)
  /casa/host/src/anatomist/anatomist-gpl/master/pyanatomist/bin/CMakeLists.txt:12 (BRAINVISA_ADD_EXECUTABLE)
```

**Environment:**
 - Engine: Singularity 
 - Version of BrainVISA master branch
 - For local builds, version of the casa-dev image: `casa-dev-5.3-25`

**Comment by denisri** [comment]
It's rather likely related to the recent change (a few months ago) where "anatomist" is no longer the C++ executable (which is now renamed "anatomist-bin") but a python script which initialized ipython/jupyter engine in order to keep working with recent jupyter qtconsole versions. I remember I had to change some things inside brainvisa-cmake to avoid a Cmake target name conflict. Either it was not enough and it happens that it was still working by chance in an existing environment, or something did not update in your brainvisa-cmake install.
Or, possibly also, a merge with the conda branch did wipe out the modif I was talking about.

**Comment by sapetnioc** [comment]
I already had this too. I thought I also made a change somewhere in brainvisa-cmake to add a suffix on some target.

**Comment by sapetnioc** [comment]
I found the commit that removed the fix: https://github.com/brainvisa/brainvisa-cmake/commit/51214a56218fa2ee08ff7b3ed06cf2fc37af566c

**Comment by denisri** [comment]
It should be redone, anyway...

**Comment by ylep** [comment]
This is indeed the fix, thanks!

However, I noticed that there is no more two-stage build of brainvisa-cmake. This means that `bv_maker sources` is not enough to apply the fix: in a fresh build environment (e.g. after emptying `/casa/host/build`) the broken version of brainvisa-cmake continues to be used, and must be patched manually to apply the fix. This is not ideal... But at least, an up-to-date version is going to be picked up when setting up a new environment with the `-B .:/casa/setup` trick.
