### ISSUE TITLE
`make install` fails to install some files that `make install-runtime` includes

### ISSUE THREAD

**Issue by ylep** [brainvisa/brainvisa-cmake#26]
In particular the files in `share` directories of `aims` are not copied by `make install`

the `install` target should probably depend on `install-runtime`

**Comment by denisri** [comment]
Well after looking a bit I remember that it was not possible (or at least not easy) to add a dependency on the "install" target, which is managed internally by cmake with the install() commands.
When looking on internet, I see that several people have run into the same problem and I haven't seen any satisfactory solution so far...

**Comment by denisri** [comment]
Well I found a way (not documlented anywhere on the internet):
`    if( NOT TARGET install )`
̀`      add_custom_target( install )`
`    endif()`
`    add_dependencies( install install-${_project} )`
But anyway this seems not to be the good path, because the install target also tries to install other things, following the CMAKE_INSTALL_PREFIX (defined at configure time) where we need to use BRAINVISA_INSTALL_PREFIX (at "make time").
So maybe the best thing is to throw an error when "make install" is invoked, and tell the user to use "make install-runtime" instead in the error message.
Would it be OK ?

**Comment by denisri** [comment]
Well I can't make it work. Apparently adding anything before the install step seems impossible in cmake...
