### ISSUE TITLE
Issue an error if LD_LIBRARY_PATH contains /.singularity.d/libs

### ISSUE THREAD

**Issue by ylep** [brainvisa/brainvisa-cmake#63]
In order to prevent build issues such as https://github.com/brainvisa/casa-distro/issues/113 caused by incorrect OpenGL libs, we should test if `LD_LIBRARY_PATH` contains `/.singularity.d/libs` and raise an error if that is the case, indicating to use the `opengl=container` option when running `bv_maker`.

**Comment by denisri** [comment]
Or we could perhaps remove it inside bv_maker. It's a bidouille but if it proves to work in every case...
The thing is that I don't remember in which exacti situation the issues happens...

**Comment by denisri** [comment]
Your modif is good in the general case (have a consistent config in cmake) but I'm not sure it fixes the issue, because:
- it happened during linking (`make` commmand, not during configure)
- at least in one case, we fixed it (temporarily) the other way: `/usr/lib/x86_64/libGL.so` was configured in the `CMakeCache.txt` but we had to manually change it to `/.singularity/libs/libGL.so` in order to make it work (which is not a good fix, I totally agree)

But I hope the fix attempt for brainvisa/casa-distro#113 (brainvisa/anatomist-free@187d854) will work.
