### ISSUE TITLE
What GitHub URL to use for private projects ?

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/brainvisa-cmake#79]
In CATI, we have one (and soon several) private project that needs brainvisa-cmake and casa-distro: catidb-client.
I do not want to develop anything specific to manage access to this project (unlike BioProj).
I declared its URL as https://gtihub.com/cati-neuroimaging/catidb-client as for all other components.
This works with access token defined in `~/.git-credentials`.
But I think it could be better to use a ssh key. I do not know this very well. For me, this makes differences for both users and `bv_maker`. So my question is double:
- What URL should we use in `components_definition.py`, `https://github.com/...` or `ssh://git@github.com/...` ?
- What procedure should we write for casa-distro users ?

**Comment by ylep** [comment]
I think we should use the `https` URL, because it does not *require* configuration. People who prefer to use SSH (like myself) can configure Git to automatically substitute the SSH url:

    git config --global url.git@github.com:.insteadOf https://github.com/

By the way, even for public projects I like to use SSH for pushing (keeping https for fetching), which can be done with

    git config --global url.git@github.com:.pushInsteadOf https://github.com/

**Comment by sapetnioc** [comment]
Thanks, the URL substitution is exactly the kind of thing I needed to know. Let's keep `https` then.
